name: autoDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Hexo Souce Repo to Tencent CloudBase
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      # Bulid Theme
      - name: Hexo Bulid Theme
        run: |
          cd ./themes/tranquilpeak/
          npm install
          npm run build
      # NPM and Hexo
      - name: Hexo NPM Install
        run: npm install
      - name: Hexo Clean
        run: ./node_modules/.bin/hexo clean
      - name: Hexo Generate
        run: ./node_modules/.bin/hexo generate
      # Deploy static to Tencent CloudBase
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          secretId: ${{ secrets.SECRETID }}
          secretKey: ${{ secrets.SECRETKEY }}
          envId: ${{ secrets.ENVID }}
          staticSrcPath: public